---
- hosts: localhost
  user: rsherman
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
  tasks:
    - name: Create Documents dir structure
      ansible.builtin.file: 
	path: /Users/rsherman/Documents/{{ item }} 
	state: directory 
	owner: rsherman 
	group: staff
      loop:
        - AWS
        - Education
        - django_projects
        - open_source_projects
        - python_objectives
        - scripts/python
        - vagrant
        - venvs
        - vpn
        - work_related


