---
- hosts: localhost
  user: rsherman
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
  tasks:
    - name: Create src dir
      ansible.builtin.file: 
	path: /Users/rsherman/src
	state: directory 
	owner: rsherman 
	group: staff


